export { default as Page } from './Page'
export { default as Meta } from './Meta'

export { NoteProvider, NoteContext } from './NoteContext'
export { default as Notes } from './Notes'
export { default as NoteList, ALL_NOTES_QUERY } from './NoteList'
export { default as NoteItem, UPDATE_NOTE_MUTATION } from './NoteItem'
export { default as CreateNote } from './CreateNote'
export { default as DeleteNote, DELETE_NOTE_MUTATION } from './DeleteNote'
export { default as NoteDetail } from './NoteDetail'
export * from './Switch'
